package com.project.iosephknecht.barcode_view.data.database;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.project.iosephknecht.barcode_view.data.database.DocumentInfo;
import com.project.iosephknecht.barcode_view.data.database.DocumentModel;

import com.project.iosephknecht.barcode_view.data.database.DocumentInfoDao;
import com.project.iosephknecht.barcode_view.data.database.DocumentModelDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig documentInfoDaoConfig;
    private final DaoConfig documentModelDaoConfig;

    private final DocumentInfoDao documentInfoDao;
    private final DocumentModelDao documentModelDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        documentInfoDaoConfig = daoConfigMap.get(DocumentInfoDao.class).clone();
        documentInfoDaoConfig.initIdentityScope(type);

        documentModelDaoConfig = daoConfigMap.get(DocumentModelDao.class).clone();
        documentModelDaoConfig.initIdentityScope(type);

        documentInfoDao = new DocumentInfoDao(documentInfoDaoConfig, this);
        documentModelDao = new DocumentModelDao(documentModelDaoConfig, this);

        registerDao(DocumentInfo.class, documentInfoDao);
        registerDao(DocumentModel.class, documentModelDao);
    }
    
    public void clear() {
        documentInfoDaoConfig.clearIdentityScope();
        documentModelDaoConfig.clearIdentityScope();
    }

    public DocumentInfoDao getDocumentInfoDao() {
        return documentInfoDao;
    }

    public DocumentModelDao getDocumentModelDao() {
        return documentModelDao;
    }

}
