package com.project.iosephknecht.barcode_view.data.database;

import java.util.List;
import java.util.ArrayList;
import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.SqlUtils;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "DOCUMENT_MODEL".
*/
public class DocumentModelDao extends AbstractDao<DocumentModel, Long> {

    public static final String TABLENAME = "DOCUMENT_MODEL";

    /**
     * Properties of entity DocumentModel.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, long.class, "id", true, "_id");
        public final static Property DocumentInfoId = new Property(1, Long.class, "documentInfoId", false, "DOCUMENT_INFO_ID");
        public final static Property CodeText = new Property(2, String.class, "codeText", false, "CODE_TEXT");
        public final static Property ModelArray = new Property(3, byte[].class, "modelArray", false, "MODEL_ARRAY");
    }

    private DaoSession daoSession;


    public DocumentModelDao(DaoConfig config) {
        super(config);
    }
    
    public DocumentModelDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
        this.daoSession = daoSession;
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"DOCUMENT_MODEL\" (" + //
                "\"_id\" INTEGER PRIMARY KEY NOT NULL ," + // 0: id
                "\"DOCUMENT_INFO_ID\" INTEGER," + // 1: documentInfoId
                "\"CODE_TEXT\" TEXT," + // 2: codeText
                "\"MODEL_ARRAY\" BLOB);"); // 3: modelArray
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"DOCUMENT_MODEL\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, DocumentModel entity) {
        stmt.clearBindings();
        stmt.bindLong(1, entity.getId());
 
        Long documentInfoId = entity.getDocumentInfoId();
        if (documentInfoId != null) {
            stmt.bindLong(2, documentInfoId);
        }
 
        String codeText = entity.getCodeText();
        if (codeText != null) {
            stmt.bindString(3, codeText);
        }
 
        byte[] modelArray = entity.getModelArray();
        if (modelArray != null) {
            stmt.bindBlob(4, modelArray);
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, DocumentModel entity) {
        stmt.clearBindings();
        stmt.bindLong(1, entity.getId());
 
        Long documentInfoId = entity.getDocumentInfoId();
        if (documentInfoId != null) {
            stmt.bindLong(2, documentInfoId);
        }
 
        String codeText = entity.getCodeText();
        if (codeText != null) {
            stmt.bindString(3, codeText);
        }
 
        byte[] modelArray = entity.getModelArray();
        if (modelArray != null) {
            stmt.bindBlob(4, modelArray);
        }
    }

    @Override
    protected final void attachEntity(DocumentModel entity) {
        super.attachEntity(entity);
        entity.__setDaoSession(daoSession);
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.getLong(offset + 0);
    }    

    @Override
    public DocumentModel readEntity(Cursor cursor, int offset) {
        DocumentModel entity = new DocumentModel( //
            cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getLong(offset + 1), // documentInfoId
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // codeText
            cursor.isNull(offset + 3) ? null : cursor.getBlob(offset + 3) // modelArray
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, DocumentModel entity, int offset) {
        entity.setId(cursor.getLong(offset + 0));
        entity.setDocumentInfoId(cursor.isNull(offset + 1) ? null : cursor.getLong(offset + 1));
        entity.setCodeText(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setModelArray(cursor.isNull(offset + 3) ? null : cursor.getBlob(offset + 3));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(DocumentModel entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(DocumentModel entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(DocumentModel entity) {
        throw new UnsupportedOperationException("Unsupported for entities with a non-null key");
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
    private String selectDeep;

    protected String getSelectDeep() {
        if (selectDeep == null) {
            StringBuilder builder = new StringBuilder("SELECT ");
            SqlUtils.appendColumns(builder, "T", getAllColumns());
            builder.append(',');
            SqlUtils.appendColumns(builder, "T0", daoSession.getDocumentInfoDao().getAllColumns());
            builder.append(" FROM DOCUMENT_MODEL T");
            builder.append(" LEFT JOIN DOCUMENT_INFO T0 ON T.\"DOCUMENT_INFO_ID\"=T0.\"_id\"");
            builder.append(' ');
            selectDeep = builder.toString();
        }
        return selectDeep;
    }
    
    protected DocumentModel loadCurrentDeep(Cursor cursor, boolean lock) {
        DocumentModel entity = loadCurrent(cursor, 0, lock);
        int offset = getAllColumns().length;

        DocumentInfo documentInfo = loadCurrentOther(daoSession.getDocumentInfoDao(), cursor, offset);
        entity.setDocumentInfo(documentInfo);

        return entity;    
    }

    public DocumentModel loadDeep(Long key) {
        assertSinglePk();
        if (key == null) {
            return null;
        }

        StringBuilder builder = new StringBuilder(getSelectDeep());
        builder.append("WHERE ");
        SqlUtils.appendColumnsEqValue(builder, "T", getPkColumns());
        String sql = builder.toString();
        
        String[] keyArray = new String[] { key.toString() };
        Cursor cursor = db.rawQuery(sql, keyArray);
        
        try {
            boolean available = cursor.moveToFirst();
            if (!available) {
                return null;
            } else if (!cursor.isLast()) {
                throw new IllegalStateException("Expected unique result, but count was " + cursor.getCount());
            }
            return loadCurrentDeep(cursor, true);
        } finally {
            cursor.close();
        }
    }
    
    /** Reads all available rows from the given cursor and returns a list of new ImageTO objects. */
    public List<DocumentModel> loadAllDeepFromCursor(Cursor cursor) {
        int count = cursor.getCount();
        List<DocumentModel> list = new ArrayList<DocumentModel>(count);
        
        if (cursor.moveToFirst()) {
            if (identityScope != null) {
                identityScope.lock();
                identityScope.reserveRoom(count);
            }
            try {
                do {
                    list.add(loadCurrentDeep(cursor, false));
                } while (cursor.moveToNext());
            } finally {
                if (identityScope != null) {
                    identityScope.unlock();
                }
            }
        }
        return list;
    }
    
    protected List<DocumentModel> loadDeepAllAndCloseCursor(Cursor cursor) {
        try {
            return loadAllDeepFromCursor(cursor);
        } finally {
            cursor.close();
        }
    }
    

    /** A raw-style query where you can pass any WHERE clause and arguments. */
    public List<DocumentModel> queryDeep(String where, String... selectionArg) {
        Cursor cursor = db.rawQuery(getSelectDeep() + where, selectionArg);
        return loadDeepAllAndCloseCursor(cursor);
    }
 
}
